# Generated by Django 4.2.13 on 2024-07-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('surname', models.CharField(max_length=500,verbose_name='surname')),
                ('age', models.IntegerField(max_length=50,verbose_name='age')),
            ],
        ),
    ]
